# Generated by Django 3.1.4 on 2021-08-02 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='auctioninfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identificador', models.CharField(max_length=20)),
                ('tipo_subasta', models.CharField(max_length=20)),
                ('fecha_inicio', models.CharField(max_length=10)),
                ('fecha_conclusion', models.CharField(max_length=10)),
                ('tasacion', models.CharField(max_length=200)),
                ('puja_minima', models.CharField(max_length=50)),
                ('importe_deposito', models.CharField(max_length=50)),
                ('cantidad_reclamada', models.CharField(max_length=50)),
                ('localidad', models.CharField(max_length=50)),
                ('descripcion', models.CharField(max_length=300)),
            ],
        ),
    ]
