# Generated by Django 3.1.4 on 2021-08-02 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('getauctions', '0002_auto_20210802_1656'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auctioninfo',
            name='descripcion',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='auctioninfo',
            name='importe_deposito',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='auctioninfo',
            name='localidad',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='auctioninfo',
            name='puja_minima',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='auctioninfo',
            name='tasacion',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
