# Generated by Django 3.1.4 on 2021-08-05 13:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('getauctions', '0003_auto_20210802_1657'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='auctioninfo',
            options={'verbose_name_plural': 'Auctions'},
        ),
    ]
