# Generated by Django 3.1.4 on 2021-08-06 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('getauctions', '0004_auto_20210805_1348'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='auctioninfo',
            name='localidad',
        ),
        migrations.AddField(
            model_name='auctioninfo',
            name='ciudad',
            field=models.CharField(blank=True, default='', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='auctioninfo',
            name='codigo_postal',
            field=models.CharField(default='', max_length=5),
        ),
        migrations.AddField(
            model_name='auctioninfo',
            name='comunidad',
            field=models.CharField(default='', max_length=25),
            preserve_default=False,
        ),
    ]
