# Generated by Django 3.1.4 on 2021-08-06 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('getauctions', '0006_auto_20210806_1449'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auctioninfo',
            name='ciudad',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='auctioninfo',
            name='codigo_postal',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='auctioninfo',
            name='correo_electronico',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
