# Generated by Django 3.1.4 on 2021-08-06 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('getauctions', '0007_auto_20210806_1454'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auctioninfo',
            name='provincia',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
    ]
