# Generated by Django 3.1.4 on 2021-08-06 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('getauctions', '0008_auto_20210806_1456'),
    ]

    operations = [
        migrations.AddField(
            model_name='auctioninfo',
            name='direccion',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
