# Generated by Django 3.1.4 on 2021-08-06 15:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('getauctions', '0009_auctioninfo_direccion'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='auctioninfo',
            unique_together={('identificador',)},
        ),
    ]
