# Generated by Django 3.2.6 on 2021-08-10 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('getauctions', '0010_auto_20210806_1525'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auctioninfo',
            name='identificador',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='auctioninfo',
            name='tipo_subasta',
            field=models.CharField(max_length=50),
        ),
    ]
