# Generated by Django 3.2.6 on 2021-08-10 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('getauctions', '0011_auto_20210810_1030'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auctioninfo',
            name='descripcion',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
