# Generated by Django 3.2.6 on 2021-08-10 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('getauctions', '0012_alter_auctioninfo_descripcion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auctioninfo',
            name='descripcion',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
