# Generated by Django 3.1 on 2021-08-20 10:06

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('getauctions', '0013_alter_auctioninfo_descripcion'),
    ]

    operations = [
        migrations.AddField(
            model_name='auctioninfo',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2021, 8, 20, 10, 6, 59, 709878, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
